import type { NextPage, NextPageContext } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Promise from 'bluebird'
import AppBar from '../components/AppBar'
import styles from '../styles/Home.module.scss'

interface CustomProps {
  userAgent?: string;
}

const Page: NextPage = ({ userAgent }: CustomProps) => {
  return (
    <>
      <Head>
        <title>Wallet - BoterinDriver</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <AppBar />
      </main>
    </>
  )
}

Page.getInitialProps = async ({ req }: NextPageContext): Promise<CustomProps> => {
  const userAgent = req ? req.headers['user-agent'] : navigator.userAgent
  return { userAgent }
}

export default Page
